Process+deps:ask user whether to skip already installed packagesFix add_item_to_queue: fallback installed check without REPO_TAG to detect packages installed from third-party repos or locall builds and install packages.
Signed-off-by: Anagnostakis Ioannis <elahistos@yahoo.gr>

diff --git a/src/usr/sbin/sbopkg b/src/usr/sbin/sbopkg
--- a/src/usr/sbin/sbopkg
+++ b/src/usr/sbin/sbopkg
@@ -1368,29 +1368,32 @@ info_item() {
                         ;;
                     "Process+deps" )
                         if ! command -v /usr/sbin/sqg &>/dev/null; then
-                           dialog --title "ERROR" --msgbox "$(crunch "sqg not found. \
-                              You have broken sbopkg or something is wrong")" 8 30
-                           break
-                        fi
-                        > $STARTQUEUE
-                        > $TMPQUEUE
-                        touch $USERQUEUE_LOCK
-                        /usr/sbin/sqg -p "$APP"
-                        if [[ -r $QUEUEDIR/$APP.sqf ]]; then
-                           parse_queue $QUEUEDIR/$APP.sqf
-                           while read PICK; do
-                               can_skip_line $PICK && continue
-                               PICK_NAME=${PICK%% *}
-                               [[ ${PICK:(-3)} == "OFF" ]] && continue
-                               grep -qx "$PICK_NAME" $STARTQUEUE || echo "$PICK_NAME" >> $STARTQUEUE
-                        done < $TMPQUEUE
-                        rm -f $TMPQUEUE $USERQUEUE_LOCK
-                        process_queue install
-                      else
-                         dialog --title "ERROR" --msgbox "$(crunch "sqg failed to \
-                             generate queue for $APP.")" 8 30
-                       fi
-                       ;;
+        dialog --title "ERROR" --msgbox "$(crunch "sqg not found. \
+            You have broken sbopkg or something is wrong")" 8 30
+        break
+    fi
+    > $STARTQUEUE
+    > $TMPQUEUE
+    touch $USERQUEUE_LOCK
+    /usr/sbin/sqg -p "$APP"
+    if [[ -r $QUEUEDIR/$APP.sqf ]]; then
+        parse_queue $QUEUEDIR/$APP.sqf
+        dialog --title "Skip installed?" --yesno \
+            "Skip already installed packages?" 6 40
+        [[ $? -eq 0 ]] && uncheck_installed $TMPQUEUE
+        while read PICK; do
+            can_skip_line $PICK && continue
+            PICK_NAME=${PICK%% *}
+            [[ ${PICK:(-3)} == "OFF" ]] && continue
+            grep -qx "$PICK_NAME" $STARTQUEUE || echo "$PICK_NAME" >> $STARTQUEUE
+        done < $TMPQUEUE
+        rm -f $TMPQUEUE $USERQUEUE_LOCK
+        process_queue install
+    else
+        dialog --title "ERROR" --msgbox "$(crunch "sqg failed to \
+            generate queue for $APP.")" 8 30
+    fi
+    ;;
                     Extract )
                         if [[ ! -z $REPO_GPG ]]; then
                             extract_tarball $SHORTPATH $REPO_DIR/$CATEGORY
@@ -2117,7 +2120,6 @@ add_item_to_queue() {
     # an APP is found in the repo, then add it to TMPQUEUE. LOADOPTIONS may be
     # supplied when parsing a queuefile or similar and are eventually passed
     # on to the SlackBuild.
-
     # If an obsolete name is used, add_item_to_queue() automatically retrieves
     # and uses the current name.
     #
@@ -2134,7 +2136,7 @@ add_item_to_queue() {
 
     # This next if is for legacy queuefiles with $APP $VERSION$BUILD $ONOFF
     if [[ $3 =~ [Oo][Ff][Ff] ]]; then
-          APP=-$APP
+        APP=-$APP
     fi
     if [[ ${APP:0:1} == "-" ]]; then
         APP=${APP:1}
@@ -2165,8 +2167,12 @@ add_item_to_queue() {
         # note that this regex was missing the ^ as of r826 and this caused a
         # false match when running 'sbopkg -k -i queue' because 'foo' and
         # 'libfoo' matched
-        INSTALLED=$(ls -1 /var/lib/pkgtools/packages/ |
+        INSTALLED=$(ls -1 /var/lib/pkgtools/packages/ | \
             grep "^$APP-[^-]*-[^-]*-[^-]*$REPO_TAG$")
+        if [[ -z $INSTALLED ]]; then
+            INSTALLED=$(ls -1 /var/lib/pkgtools/packages/ | \
+                grep "^$APP-[^-]*-[^-]*-[^-]*$")
+        fi
         if [[ -n $INSTALLED ]]; then
             VERSION=$(sed 's:^.*-\([^-]*\)-[^-]*-[^-]*$:\1:'<<<$INSTALLED)
             if [[ -e $UPDATELIST ]]; then
