many whitespace cleanups; added timeout to rsync call; separated rsync_command from rsync_repo in order to keep the dialog box in state while rsync is performed, similar to what happens when a build occurs; there are still some old commented out code for the time being; general cleanups

diff --git a/src/usr/bin/sbopkg b/src/usr/bin/sbopkg
--- a/src/usr/bin/sbopkg
+++ b/src/usr/bin/sbopkg
@@ -31,16 +31,16 @@ SCRIPT=${0##*/}
 DIAG=""
 SBOPKG_CONF="${SBOPKG_CONF:-/etc/sbopkg/sbopkg.conf}"
 CWD="$pwd"
-VER=0.0.2
+VER=0.0.3
 
 sanity_checks () {
 # Check if config file is there and if yes, set some variables
 if [ ! -e $SBOPKG_CONF ]; then
     echo "$SCRIPT: No $SBOPKG_CONF file was found."
     echo "Please create it and run $SCRIPT again." 1>&2
-	exit 1
+    exit 1
 else
-	. $SBOPKG_CONF
+    . $SBOPKG_CONF
 fi
 if [ ! -d "$SRCDIR" ]; then
     echo "Creating local cache directory $SRCDIR to keep \
@@ -52,20 +52,20 @@ fi
 check_local_dir () {
 # Check to see if the main local directory for the mirror exists
 if [ ! -d "$LOCALREPO/$SLACKVER" ]; then
-	echo "$SCRIPT: Directory $LOCALREPO/$SLACKVER does not exist."
+    echo "$SCRIPT: Directory $LOCALREPO/$SLACKVER does not exist."
     echo "Please create it and run $SCRIPT again." 1>&2
-	exit 1
+    exit 1
 else
- 	cd $LOCALREPO/$SLACKVER
+    cd $LOCALREPO/$SLACKVER
 fi
 }
 
 check_root () {
 # Check to see whether the user is root or not
 if [ ! $(id -u) = "0" ]; then
-	ROOT="false"
+    ROOT="false"
 else
-	ROOT="true"
+    ROOT="true"
 fi
 }
 
@@ -81,10 +81,10 @@ fi
 show_changelog () {
 # Show the changelog
 if [ "$DIAG" = 1 ]; then
-	dialog --title "SlackBuilds.org ChangeLog" --textbox \
+    dialog --title "SlackBuilds.org ChangeLog" --textbox \
     ./ChangeLog.txt 0 0
 else
-	${PAGER:-more} ./ChangeLog.txt
+    ${PAGER:-more} ./ChangeLog.txt
 fi
 }
 
@@ -93,10 +93,10 @@ get_category_list () {
 rm -f $TMP/sbopkg_category_list 2> /dev/null
 DIR=( */ )
 if [ -n "$DIR" ]; then
-	for i in ${DIR[*]%/}; do
-		echo "$i \"Browse the $i category\"" >> \
+    for i in ${DIR[*]%/}; do
+        echo "$i \"Browse the $i category\"" >> \
         $TMP/sbopkg_category_list
-	done
+    done
 fi
 }
 
@@ -110,10 +110,10 @@ cd $LOCALREPO/$SLACKVER/$CATEGORY
 rm -f $TMP/sbopkg_category_items_list 2> /dev/null
 DIR=( */ )
 if [ -n "$DIR" ]; then
-	for i in ${DIR[*]%/}; do
-		DESC=$(grep -h -Z -m1 ^$i ./$i/slack-desc* | sed -e s/$i': '//) 
-		echo "$i \"$DESC\"" >> $TMP/sbopkg_category_items_list
-	done
+    for i in ${DIR[*]%/}; do
+        DESC=$(grep -h -Z -m1 ^$i ./$i/slack-desc* | sed -e s/$i': '//) 
+        echo "$i \"$DESC\"" >> $TMP/sbopkg_category_items_list
+    done
 fi
 cd $LOCALREPO/$SLACKVER
 }
@@ -132,45 +132,47 @@ dialog --title "$APP Information" --menu "Choose an item or press \
 "Build" "Build a package for $APP" 2>$TMP/sbopkg_info_selection
 
 if [ $? = 1 ]; then
-	break
+    break
 fi
 S="$(cat $TMP/sbopkg_info_selection)"
 CATEGORY="$(cat $TMP/sbopkg_category_selection)"
 if [ "$S" = "README" ]; then
-	dialog --title "Viewing README" \
+    dialog --title "Viewing README" \
     --textbox $LOCALREPO/$SLACKVER/$CATEGORY/$APP/README 0 0
 fi
 if [ "$S" = "SlackBuild" ]; then
-	dialog --title "Viewing SlackBuild" \
+    dialog --title "Viewing SlackBuild" \
     --textbox $LOCALREPO/$SLACKVER/$CATEGORY/$APP/$APP.SlackBuild 0 0
 fi
 if [ "$S" = "Info" ]; then
-	dialog --title "Viewing .info" \
+    dialog --title "Viewing .info" \
     --textbox $LOCALREPO/$SLACKVER/$CATEGORY/$APP/$APP.info 0 0
 fi
 if [ "$S" = "Slack-desc" ]; then
 PARSED_SLACK_DESC=$(mktemp $TMP/sbopkg_parsed_slack_desc.XXXXXX)
 sed -n "/^$APP: /s///p" $LOCALREPO/$SLACKVER/$CATEGORY/$APP/slack-desc > $PARSED_SLACK_DESC
-	dialog --title "Viewing Slack-desc" --textbox $PARSED_SLACK_DESC 0 0
+    dialog --title "Viewing Slack-desc" --textbox $PARSED_SLACK_DESC 0 0
 fi
 if [ "$S" = "Build" ]; then
-	check_root
-	if [ $ROOT = "false" ]; then
-		dialog --title "ERROR" --msgbox "You must run this script \
+    check_root
+    if [ $ROOT = "false" ]; then
+        dialog --title "ERROR" --msgbox "You must run this script \
 as the root user in order to build packages." 0 0
-		continue
-	fi
-	OUTPUT=$TMP/sbopkg_output
-	search_package $APP	
-	( build_package $APP >> $OUTPUT & ) 2>>$OUTPUT
-	while [ -f $TMP/sbopkg_build.lck ]; do
-		dialog --backtitle "Building the $APP package in the \
+        continue
+    fi
+    OUTPUT=$TMP/sbopkg_output
+    search_package $APP	
+    rm -rf $TMP/sbopkg_build.lck
+    touch $TMP/sbopkg_build.lck
+    ( build_package $APP >> $OUTPUT & ) 2>>$OUTPUT
+    while [ -f $TMP/sbopkg_build.lck ]; do
+        dialog --backtitle "Building the $APP package in the \
 background." --tailbox $OUTPUT 20 70
-	done
-	if [ "$LOGS" = "YES" ]; then 
-		cat $OUTPUT >> $TMP/sbopkg-build-log
-	fi
-	rm -f $OUTPUT
+    done
+    if [ "$LOGS" = "YES" ]; then 
+        cat $OUTPUT >> $TMP/sbopkg-build-log
+    fi
+    rm -f $OUTPUT
 fi
 done
 }
@@ -180,13 +182,13 @@ browse_items () {
 # one is chosen.
 get_category_items_list
 while [ 0 ]; do
-	dialog --title "Browsing the $CATEGORY category" \
+    dialog --title "Browsing the $CATEGORY category" \
 --menu "Please select a software package" 20 70 15 \
 --file $TMP/sbopkg_category_items_list 2>$TMP/sbopkg_item_selection
-	if [ $? = 1 ]; then
-		break
-	fi
-	info_item
+    if [ $? = 1 ]; then
+        break
+    fi
+    info_item
 done
 }
 
@@ -195,13 +197,13 @@ browse_categories () {
 # chosen.
 get_category_list
 while [ 0 ]; do
-	dialog --title "Choose a category" --menu "Please select the \
+    dialog --title "Choose a category" --menu "Please select the \
 category you wish to browse." 20 70 12 \
 --file $TMP/sbopkg_category_list 2>$TMP/sbopkg_category_selection
-	if [ $? = 1 ]; then
-		break
-	fi
-	browse_items
+    if [ $? = 1 ]; then
+        break
+    fi
+    browse_items
 done
 }
 
@@ -210,6 +212,13 @@ view_cache_dir () {
 ls -la $SRCDIR > $TMP/sbopkg_cache_dir
 dialog --title "Displaying $SRCDIR" \
 --textbox $TMP/sbopkg_cache_dir 0 0
+}
+
+rsync_command () {
+# This function holds the rsync command
+/usr/bin/rsync -avz --delete --timeout=5 \
+$RSYNCMIRROR/$SLACKVER/ $LOCALREPO/$SLACKVER/ 
+rm -rf $TMP/sbopkg_rsync.lck
 }
 
 rsync_repo () {
@@ -222,19 +231,24 @@ permissions on the target directory." 0 0
         continue
     else
         echo "You do not have write permissons on the target directory."
-		exit 0
-	fi
+        exit 0
+    fi
 fi
 if [ "$DIAG" = 1 ]; then
-	OUTPUT=$TMP/sbopkg_output
-	( /usr/bin/rsync -avz --delete $RSYNCMIRROR/$SLACKVER/ \
-$LOCALREPO/$SLACKVER/ >> $OUTPUT & ) 2>>$OUTPUT
-	dialog --backtitle "Rsyncing with SlackBuilds.org" \
---tailbox $OUTPUT 20 70
-	rm -f $OUTPUT
+    rm -rf $TMP/sbopkg_rsync.lck
+    touch $TMP/sbopkg_rsync.lck
+    OUTPUT=$TMP/sbopkg_output
+    #( /usr/bin/rsync -avz --delete --dry-run --timeout=5 --contimeout=5 $RSYNCMIRROR/$SLACKVER/ \
+    ( rsync_command >> $OUTPUT & ) 2>>$OUTPUT 
+    while [ -f $TMP/sbopkg_rsync.lck ]; do
+        dialog --backtitle "Rsyncing with SlackBuilds.org" \
+--tailbox $OUTPUT 20 70 
+    done
+    rm -f $OUTPUT
 else
-	/usr/bin/rsync -avz --delete \
-$RSYNCMIRROR/$SLACKVER/ $LOCALREPO/$SLACKVER/
+#    /usr/bin/rsync -avz --delete \
+#$RSYNCMIRROR/$SLACKVER/ $LOCALREPO/$SLACKVER/
+    rsync_command
 fi
 }
 
@@ -244,14 +258,14 @@ search_package () {
 # displaying information and building.
 PKG=$1
 PKGPATH=$(find -name $PKG)  
-if [ ! $( find -name "$PKG") ]; then 
-	if [ "$DIAG" = 1 ]; then
-		dialog --title "ERROR" --msgbox "Package $PKG not found" 0 0
-		continue
-	else
-		echo "$SCRIPT: Package $PKG not found.  Exiting." 1>&2
-		exit 1
-	fi
+if [ ! $(find -name "$PKG") ]; then 
+    if [ "$DIAG" = 1 ]; then
+        dialog --title "ERROR" --msgbox "Package $PKG not found" 0 0
+        continue
+    else
+        echo "$SCRIPT: Package $PKG not found.  Exiting." 1>&2
+        exit 1
+    fi
 fi
 . $PKGPATH/$PKG.info
 PKGNAME=${PKG##*/}
@@ -260,7 +274,6 @@ SRCNAME=${DOWNLOAD##*/}
 
 show_readme () {
 # Show the package's text files.
-# Add iteration of other standard files
 SBODOCS="README $PKGNAME.SlackBuild $PKGNAME.info slack-desc"
 for i in $SBODOCS; do
     ${PAGER:-more} $PKGPATH/$i
@@ -286,22 +299,21 @@ fi
 
 build_package () {
 # Start fetching and building the package.
-touch $TMP/sbopkg_build.lck
 echo ; echo "Building $PKG"
 cd $PKGPATH
 get_source
 echo "Checking MD5SUM for "$SRCNAME"..."
-MD5CHK=`md5sum $SRCNAME | cut -d' ' -f1`
+MD5CHK=$(md5sum $SRCNAME | cut -d' ' -f1)
 if [ "$MD5CHK" == $MD5SUM ]; then 
-	echo "OK"
+    echo "OK"
 else 
-	echo "MD5SUM check failed.  Exiting." 
-	continue
+    echo "MD5SUM check failed.  Exiting." 
+    continue
 fi
 echo "Building Slackware package for "$SRCNAME"..."
-TMP=$TMP sh $PKG.SlackBuild
+sh $PKG.SlackBuild
 echo "Done building $PKG."
-rm $TMP/sbopkg_build.lck
+rm -rf $TMP/sbopkg_build.lck
 cd $LOCALREPO/$SLACKVER
 }
 
@@ -324,23 +336,23 @@ dialog --title "SlackBuilds.org Package Browser \
 "Exit" "Exit sbopkg" 2>$TMP/sbopkg_main_menu_answer
 
 if [ $? = 1 ]; then
-	clear
-	cleanup
-	exit 0
+    clear
+    cleanup
+    exit 0
 fi
 
 R="$(cat $TMP/sbopkg_main_menu_answer)"
 
 if [ "$R" = "Rsync" ]; then
-	rsync_repo
+    rsync_repo
 fi
 
 if [ "$R" = "ChangeLog" ]; then
-	show_changelog
+    show_changelog
 fi
 
 if [ "$R" = "Browse" ]; then
-	browse_categories
+    browse_categories
 fi
 
 if [ "$R" = "Cache" ]; then
@@ -348,9 +360,9 @@ if [ "$R" = "Cache" ]; then
 fi
 
 if [ "$R" = "Exit" ]; then
-	clear
-	cleanup
-	exit 0 
+    clear
+    cleanup
+    exit 0 
 fi
 done
 }
@@ -360,53 +372,56 @@ done
 
 # If there are no command line options then we will use the dialog
 # version of sbopkg
+
+cleanup
+
 if [ $# -eq 0 ]; then 
-	DIAG=1
-	sanity_checks
-	check_local_dir
-	main_menu
-	exit 0
+    DIAG=1
+    sanity_checks
+    check_local_dir
+    main_menu
+    exit 0
 fi
 
 # This is the command line options and help
 while getopts ":b:d:f:hlrs:" OPT; do
-	case $OPT in
-		b ) BUILD="$OPTARG"
-			;;
-		d ) LOCALREPO="$OPTARG"
-			;;
-		f ) SBOPKG_CONF="$OPTARG"
-			;;
-		l ) CHANGELOG=1
-			;;
-		r ) RSYNC=1
-			;;
-		s ) SEARCH="$OPTARG"
-			;;
-		h|* )
-			echo
-	 		echo "$SCRIPT v$VER"
-			echo "Usage: $SCRIPT [OPTIONS] <packagename(s)>"
-			echo "Options are:"
-			echo "  -b package   Build a package."
-			echo "  -d localdir  Location of local copy of \
+    case $OPT in
+        b ) BUILD="$OPTARG"
+            ;;
+        d ) LOCALREPO="$OPTARG"
+            ;;
+        f ) SBOPKG_CONF="$OPTARG"
+            ;;
+        l ) CHANGELOG=1
+            ;;
+        r ) RSYNC=1
+            ;;
+        s ) SEARCH="$OPTARG"
+            ;;
+        h|* )
+            echo
+            echo "$SCRIPT v$VER"
+            echo "Usage: $SCRIPT [OPTIONS] <packagename(s)>"
+            echo "Options are:"
+            echo "  -b package   Build a package."
+            echo "  -d localdir  Location of local copy of \
 SlackBuilds.org repo."
             echo "  -f           Override default configuration file" 
             echo "               with specified file or environmental \
 variables."
-			echo "  -h           Display this help message."
-			echo "  -l           Display the SlackBuilds.org \
+            echo "  -h           Display this help message."
+            echo "  -l           Display the SlackBuilds.org \
 ChangeLog.txt and then quit."
-			echo "  -r           Rsync the SlackBuilds.org respository with"
-			echo "               the local mirror and then quit."
-			echo "  -s package   Search for a package and, if found, \
+            echo "  -r           Rsync the SlackBuilds.org respository with"
+            echo "               the local mirror and then quit."
+            echo "  -s package   Search for a package and, if found, \
 display the README."
-			echo
+            echo
             echo "Note: multiple arguments to -b and -s must be \
 quoted (\"pkg1 pkg2\")"
-			exit
-			;;
-	esac
+            exit
+            ;;
+    esac
 done
 # End of option parsing.
 shift $(($OPTIND - 1))
@@ -416,42 +431,42 @@ sanity_checks
 check_local_dir
 
 if [ -n "$BUILD" ]; then
-	check_root
-	if [ $ROOT = "false" ]; then
-		echo "You must run this script as the root user in order \
+    check_root
+    if [ $ROOT = "false" ]; then
+        echo "You must run this script as the root user in order \
 to build packages."
-		exit 0
-	fi
-	for PKGBUILD in $BUILD; do
-		echo "Building $PKGBUILD"
-		search_package $PKGBUILD
-		build_package $PKGBUILD
-	done
-	cleanup
-	exit 0
+        exit 0
+    fi
+    for PKGBUILD in $BUILD; do
+        echo "Building $PKGBUILD"
+        search_package $PKGBUILD
+        build_package $PKGBUILD
+    done
+    cleanup
+    exit 0
 fi
 
 if [ -n "$CHANGELOG" ]; then
-	show_changelog
-	cleanup
-	exit 0
+    show_changelog
+    cleanup
+    exit 0
 fi
 
 if [ -n "$RSYNC" ]; then
-	echo "Rsyncing with Slackbuilds.org repository into $LOCALREPO."
-	rsync_repo
-	cleanup
-	echo "Finished rsync."
-	exit 0
+    echo "Rsyncing with Slackbuilds.org repository into $LOCALREPO."
+    rsync_repo
+    cleanup
+    echo "Finished rsync."
+    exit 0
 fi
 
 if [ -n "$SEARCH" ]; then
-	for PKGSEARCH in $SEARCH; do
-		echo "Searching for $PKGSEARCH"
-		search_package $PKGSEARCH
-		show_readme
-	done
-	exit 0
+    for PKGSEARCH in $SEARCH; do
+        echo "Searching for $PKGSEARCH"
+        search_package $PKGSEARCH
+        show_readme
+    done
+    exit 0
 fi
 
 cleanup
